[2025-05-13T13:12:10.910+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: POC_orange_data2.spark_task2 scheduled__2025-05-12T00:00:00+00:00 [queued]>
[2025-05-13T13:12:10.949+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: POC_orange_data2.spark_task2 scheduled__2025-05-12T00:00:00+00:00 [queued]>
[2025-05-13T13:12:10.949+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-05-13T13:12:10.989+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): spark_task2> on 2025-05-12 00:00:00+00:00
[2025-05-13T13:12:11.004+0000] {standard_task_runner.py:57} INFO - Started process 201 to run task
[2025-05-13T13:12:11.015+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'POC_orange_data2', 'spark_task2', 'scheduled__2025-05-12T00:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/pass_data.py', '--cfg-path', '/tmp/tmp4upu24a7']
[2025-05-13T13:12:11.024+0000] {standard_task_runner.py:85} INFO - Job 171: Subtask spark_task2
[2025-05-13T13:12:11.202+0000] {task_command.py:416} INFO - Running <TaskInstance: POC_orange_data2.spark_task2 scheduled__2025-05-12T00:00:00+00:00 [running]> on host 8fab0bc9647a
[2025-05-13T13:12:12.151+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='POC_orange_data2' AIRFLOW_CTX_TASK_ID='spark_task2' AIRFLOW_CTX_EXECUTION_DATE='2025-05-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-12T00:00:00+00:00'
[2025-05-13T13:12:12.154+0000] {logging_mixin.py:154} INFO - === Starting Spark CSV Processing DAG ===
[2025-05-13T13:12:56.216+0000] {logging_mixin.py:154} INFO - [INFO] Spark session successfully created.
[2025-05-13T13:12:56.216+0000] {logging_mixin.py:154} INFO - [INFO] Looking for CSV files in directory: /opt/***/data
[2025-05-13T13:12:56.218+0000] {logging_mixin.py:154} INFO - [INFO] 34 file(s) found for processing.
[2025-05-13T13:12:56.218+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 1/34: /opt/***/data/generated_data_1.csv
[2025-05-13T13:13:22.198+0000] {logging_mixin.py:154} INFO - [INFO] File /opt/***/data/generated_data_1.csv successfully read with 2000000 rows.
[2025-05-13T13:13:22.199+0000] {logging_mixin.py:154} INFO - [INFO] Applying sampling transformation...
[2025-05-13T13:13:23.531+0000] {logging_mixin.py:154} INFO - [INFO] Sampled DataFrame has 600876 rows.
[2025-05-13T13:13:23.532+0000] {logging_mixin.py:154} INFO - [INFO] Writing to Elasticsearch...
[2025-05-13T13:14:47.298+0000] {logging_mixin.py:154} INFO - [SUCCESS] Successfully processed and indexed: /opt/***/data/generated_data_1.csv
[2025-05-13T13:14:47.299+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 2/34: /opt/***/data/generated_data_10.csv
[2025-05-13T13:15:01.143+0000] {logging_mixin.py:154} INFO - [INFO] File /opt/***/data/generated_data_10.csv successfully read with 2000000 rows.
[2025-05-13T13:15:01.146+0000] {logging_mixin.py:154} INFO - [INFO] Applying sampling transformation...
[2025-05-13T13:15:03.165+0000] {logging_mixin.py:154} INFO - [INFO] Sampled DataFrame has 600869 rows.
[2025-05-13T13:15:03.167+0000] {logging_mixin.py:154} INFO - [INFO] Writing to Elasticsearch...
[2025-05-13T13:16:00.707+0000] {logging_mixin.py:154} INFO - [SUCCESS] Successfully processed and indexed: /opt/***/data/generated_data_10.csv
[2025-05-13T13:16:00.709+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 3/34: /opt/***/data/generated_data_11.csv
[2025-05-13T13:16:11.673+0000] {logging_mixin.py:154} INFO - [INFO] File /opt/***/data/generated_data_11.csv successfully read with 2000000 rows.
[2025-05-13T13:16:11.674+0000] {logging_mixin.py:154} INFO - [INFO] Applying sampling transformation...
[2025-05-13T13:16:12.802+0000] {logging_mixin.py:154} INFO - [INFO] Sampled DataFrame has 600869 rows.
[2025-05-13T13:16:12.804+0000] {logging_mixin.py:154} INFO - [INFO] Writing to Elasticsearch...
[2025-05-13T13:17:04.285+0000] {logging_mixin.py:154} INFO - [SUCCESS] Successfully processed and indexed: /opt/***/data/generated_data_11.csv
[2025-05-13T13:17:04.286+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 4/34: /opt/***/data/generated_data_12.csv
[2025-05-13T13:17:14.408+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-05-13T13:17:14.432+0000] {process_utils.py:131} INFO - Sending 15 to group 201. PIDs of all processes in the group: [207, 201]
[2025-05-13T13:17:14.433+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 201
[2025-05-13T13:17:14.453+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-05-13T13:17:14.458+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-05-13T13:17:14.480+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:14.484+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2025-05-13T13:17:14.500+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:14.501+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_12.csv: An error occurred while calling o88.count
[2025-05-13T13:17:14.502+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 5/34: /opt/***/data/generated_data_13.csv
[2025-05-13T13:17:15.822+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_13.csv: An error occurred while calling o92.csv.
: java.lang.IllegalStateException: Cannot call methods on a stopped SparkContext.
This stopped SparkContext was created at:

org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
py4j.Gateway.invoke(Gateway.java:238)
py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
py4j.ClientServerConnection.run(ClientServerConnection.java:106)
java.base/java.lang.Thread.run(Thread.java:829)

The currently active SparkContext was created at:

org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:58)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:247)
py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
py4j.Gateway.invoke(Gateway.java:238)
py4j.commands.ConstructorCommand.invokeConstructor(ConstructorCommand.java:80)
py4j.commands.ConstructorCommand.execute(ConstructorCommand.java:69)
py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
py4j.ClientServerConnection.run(ClientServerConnection.java:106)
java.base/java.lang.Thread.run(Thread.java:829)
         
	at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:122)
	at org.apache.spark.SparkContext.broadcastInternal(SparkContext.scala:1659)
	at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1644)
	at org.apache.spark.sql.execution.datasources.text.TextFileFormat.buildReader(TextFileFormat.scala:106)
	at org.apache.spark.sql.execution.datasources.FileFormat.buildReaderWithPartitionValues(FileFormat.scala:138)
	at org.apache.spark.sql.execution.datasources.FileFormat.buildReaderWithPartitionValues$(FileFormat.scala:129)
	at org.apache.spark.sql.execution.datasources.TextBasedFileFormat.buildReaderWithPartitionValues(FileFormat.scala:346)
	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD$lzycompute(DataSourceScanExec.scala:548)
	at org.apache.spark.sql.execution.FileSourceScanExec.inputRDD(DataSourceScanExec.scala:537)
	at org.apache.spark.sql.execution.FileSourceScanExec.doExecute(DataSourceScanExec.scala:575)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:195)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:246)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:243)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:191)
	at org.apache.spark.sql.execution.InputAdapter.inputRDD(WholeStageCodegenExec.scala:527)
	at org.apache.spark.sql.execution.InputRDDCodegen.inputRDDs(WholeStageCodegenExec.scala:455)
	at org.apache.spark.sql.execution.InputRDDCodegen.inputRDDs$(WholeStageCodegenExec.scala:454)
	at org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:498)
	at org.apache.spark.sql.execution.FilterExec.inputRDDs(basicPhysicalOperators.scala:242)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:751)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:195)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:246)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:243)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:191)
	at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:364)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:498)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:483)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:61)
	at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:4344)
	at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:3326)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4334)
	at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:4332)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4332)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:3326)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:3549)
	at org.apache.spark.sql.execution.datasources.csv.TextInputCSVDataSource$.infer(CSVDataSource.scala:111)
	at org.apache.spark.sql.execution.datasources.csv.CSVDataSource.inferSchema(CSVDataSource.scala:64)
	at org.apache.spark.sql.execution.datasources.csv.CSVFileFormat.inferSchema(CSVFileFormat.scala:62)
	at org.apache.spark.sql.execution.datasources.DataSource.$anonfun$getOrInferFileFormatSchema$11(DataSource.scala:208)
	at scala.Option.orElse(Option.scala:447)
	at org.apache.spark.sql.execution.datasources.DataSource.getOrInferFileFormatSchema(DataSource.scala:205)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:407)
	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:538)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
	at java.base/java.lang.Thread.run(Thread.java:829)
[2025-05-13T13:17:15.824+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 6/34: /opt/***/data/generated_data_14.csv
[2025-05-13T13:17:17.003+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty
[2025-05-13T13:17:17.004+0000] {clientserver.py:538} INFO - Error while receiving.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
[2025-05-13T13:17:17.008+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.009+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.011+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 516, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2025-05-13T13:17:17.012+0000] {java_gateway.py:1055} ERROR - Exception while sending command.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 511, in send_command
    answer = smart_decode(self.stream.readline()[:-1])
  File "/usr/local/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/airflow/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 539, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending or receiving
[2025-05-13T13:17:17.014+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.016+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.017+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_14.csv: An error occurred while calling o100.csv
[2025-05-13T13:17:17.019+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 7/34: /opt/***/data/generated_data_15.csv
[2025-05-13T13:17:17.020+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.021+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.021+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.022+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_15.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.023+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.024+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 8/34: /opt/***/data/generated_data_16.csv
[2025-05-13T13:17:17.024+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.025+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.026+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.027+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_16.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.028+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.029+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.030+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 9/34: /opt/***/data/generated_data_17.csv
[2025-05-13T13:17:17.031+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.032+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.033+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.034+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.034+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_17.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.036+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.036+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.037+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 10/34: /opt/***/data/generated_data_18.csv
[2025-05-13T13:17:17.038+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.040+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.040+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.045+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.046+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_18.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.047+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.048+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.050+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.050+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 11/34: /opt/***/data/generated_data_19.csv
[2025-05-13T13:17:17.052+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.052+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.053+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.053+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_19.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.054+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.054+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 12/34: /opt/***/data/generated_data_2.csv
[2025-05-13T13:17:17.055+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.056+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.057+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.058+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_2.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.059+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.060+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 13/34: /opt/***/data/generated_data_20.csv
[2025-05-13T13:17:17.060+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.062+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.062+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.064+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_20.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.065+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.066+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.067+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 14/34: /opt/***/data/generated_data_21.csv
[2025-05-13T13:17:17.068+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.070+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.071+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.072+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_21.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.072+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.073+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 15/34: /opt/***/data/generated_data_22.csv
[2025-05-13T13:17:17.073+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.074+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.075+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_22.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.076+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.076+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.077+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 16/34: /opt/***/data/generated_data_23.csv
[2025-05-13T13:17:17.078+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.079+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.079+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_23.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.080+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.080+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 17/34: /opt/***/data/generated_data_24.csv
[2025-05-13T13:17:17.081+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.082+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.082+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.083+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_24.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.084+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.084+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 18/34: /opt/***/data/generated_data_25.csv
[2025-05-13T13:17:17.085+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.086+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.086+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.088+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_25.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.089+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.089+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 19/34: /opt/***/data/generated_data_26.csv
[2025-05-13T13:17:17.090+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.091+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.092+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.093+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_26.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.095+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.095+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.096+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 20/34: /opt/***/data/generated_data_27.csv
[2025-05-13T13:17:17.097+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.098+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.099+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.100+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_27.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.100+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.101+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.102+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 21/34: /opt/***/data/generated_data_28.csv
[2025-05-13T13:17:17.103+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.104+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.104+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.106+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.107+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_28.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.108+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.108+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 22/34: /opt/***/data/generated_data_29.csv
[2025-05-13T13:17:17.109+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.110+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.111+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.111+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.112+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_29.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.114+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.114+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 23/34: /opt/***/data/generated_data_3.csv
[2025-05-13T13:17:17.115+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.116+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.116+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.118+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_3.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.118+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.119+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.120+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 24/34: /opt/***/data/generated_data_30.csv
[2025-05-13T13:17:17.120+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.121+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.122+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_30.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.123+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.123+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 25/34: /opt/***/data/generated_data_31.csv
[2025-05-13T13:17:17.124+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.124+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.125+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.126+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_31.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.127+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.128+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 26/34: /opt/***/data/generated_data_32.csv
[2025-05-13T13:17:17.128+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.129+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.130+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.131+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.132+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.132+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_32.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.133+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.133+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 27/34: /opt/***/data/generated_data_33.csv
[2025-05-13T13:17:17.134+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.135+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.135+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.136+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_33.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.137+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.137+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.138+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.138+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 28/34: /opt/***/data/generated_data_34.csv
[2025-05-13T13:17:17.140+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.140+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.142+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.143+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_34.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.143+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.144+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 29/34: /opt/***/data/generated_data_4.csv
[2025-05-13T13:17:17.144+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.145+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.146+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_4.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.146+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.147+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 30/34: /opt/***/data/generated_data_5.csv
[2025-05-13T13:17:17.147+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.148+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.149+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.149+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.151+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_5.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.151+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.152+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 31/34: /opt/***/data/generated_data_6.csv
[2025-05-13T13:17:17.152+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.153+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.154+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.155+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_6.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.155+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.156+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 32/34: /opt/***/data/generated_data_7.csv
[2025-05-13T13:17:17.156+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.157+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.157+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.158+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_7.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.158+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.159+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 33/34: /opt/***/data/generated_data_8.csv
[2025-05-13T13:17:17.160+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.160+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.161+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.162+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.163+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.165+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_8.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.166+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.167+0000] {logging_mixin.py:154} INFO - [INFO] Processing file 34/34: /opt/***/data/generated_data_9.csv
[2025-05-13T13:17:17.168+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.169+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.170+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.171+0000] {logging_mixin.py:154} INFO - [ERROR] Failed to process file /opt/***/data/generated_data_9.csv: [Errno 111] Connection refused
[2025-05-13T13:17:17.172+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.173+0000] {logging_mixin.py:154} INFO - [INFO] Stopping Spark session.
[2025-05-13T13:17:17.174+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.175+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.176+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.176+0000] {logging_mixin.py:154} INFO - [FATAL] Spark processing failed: [Errno 111] Connection refused
[2025-05-13T13:17:17.177+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.177+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.178+0000] {python.py:194} INFO - Done. Returned value was: Failed: [Errno 111] Connection refused
[2025-05-13T13:17:17.184+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.185+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.186+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.187+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.188+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.189+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.190+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.191+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.191+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.192+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.193+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.194+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.195+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.196+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.197+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.203+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.204+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.205+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.206+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.207+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.213+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.219+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.220+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.221+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.222+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.223+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.224+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.224+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.225+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.230+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.234+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2025-05-13T13:17:17.272+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=POC_orange_data2, task_id=spark_task2, execution_date=20250512T000000, start_date=20250513T131210, end_date=20250513T131717
[2025-05-13T13:17:17.342+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=207, status='terminated', started='13:12:11') (207) terminated with exit code None
[2025-05-13T13:17:17.344+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=201, status='terminated', exitcode=0, started='13:12:10') (201) terminated with exit code 0
[2025-05-13T13:17:17.345+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2025-05-13T13:17:17.389+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
