[2025-04-14T10:35:21.898+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: POC_orange_data2.spark_task2 scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T10:35:21.928+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: POC_orange_data2.spark_task2 scheduled__2025-04-13T00:00:00+00:00 [queued]>
[2025-04-14T10:35:21.929+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-04-14T10:35:21.972+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): spark_task2> on 2025-04-13 00:00:00+00:00
[2025-04-14T10:35:21.987+0000] {standard_task_runner.py:57} INFO - Started process 198 to run task
[2025-04-14T10:35:22.001+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'POC_orange_data2', 'spark_task2', 'scheduled__2025-04-13T00:00:00+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/pass_data.py', '--cfg-path', '/tmp/tmp6jexzn4n']
[2025-04-14T10:35:22.010+0000] {standard_task_runner.py:85} INFO - Job 133: Subtask spark_task2
[2025-04-14T10:35:22.774+0000] {task_command.py:416} INFO - Running <TaskInstance: POC_orange_data2.spark_task2 scheduled__2025-04-13T00:00:00+00:00 [running]> on host 4a94571b9623
[2025-04-14T10:35:22.959+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='POC_orange_data2' AIRFLOW_CTX_TASK_ID='spark_task2' AIRFLOW_CTX_EXECUTION_DATE='2025-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-13T00:00:00+00:00'
[2025-04-14T10:35:30.938+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pass_data.py", line 12, in spark_processing
    spark = SparkSession.builder \
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/sql/session.py", line 497, in getOrCreate
    sc = SparkContext.getOrCreate(sparkConf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 515, in getOrCreate
    SparkContext(conf=conf or SparkConf())
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 201, in __init__
    SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/context.py", line 436, in _ensure_initialized
    SparkContext._gateway = gateway or launch_gateway(conf)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyspark/java_gateway.py", line 107, in launch_gateway
    raise PySparkRuntimeError(
pyspark.errors.exceptions.base.PySparkRuntimeError: [JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.
[2025-04-14T10:35:30.962+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=POC_orange_data2, task_id=spark_task2, execution_date=20250413T000000, start_date=20250414T103521, end_date=20250414T103530
[2025-04-14T10:35:30.993+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 133 for task spark_task2 ([JAVA_GATEWAY_EXITED] Java gateway process exited before sending its port number.; 198)
[2025-04-14T10:35:31.030+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-04-14T10:35:31.054+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
